//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasksVariant
    {
        public int ID { get; set; }
        public int VariantId { get; set; }
        public int TaskId { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual Variant Variant { get; set; }
    }
}
