//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.TasksVariants = new HashSet<TasksVariant>();
            this.TaskImages = new HashSet<TaskImage>();
            this.TaskFiles = new HashSet<TaskFile>();
        }
    
        public int ID { get; set; }
        public int TaskNumberId { get; set; }
        public string Description { get; set; }
        public string Solution { get; set; }
        public string Answer { get; set; }
        public int TaskTypeId { get; set; }
    
        public virtual TaskNumber TaskNumber { get; set; }
        public virtual TaskType TaskType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasksVariant> TasksVariants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskImage> TaskImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskFile> TaskFiles { get; set; }
    }
}
